plugins {
    id("ostomate.kmp-library")
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinxSerialization)
    jacoco
}

compose.resources {
    packageOfResClass = "com.ostomate.app.resources"
}

kotlin {
    // No iosX64: Compose Multiplatform 1.11+ does not publish Intel-simulator
    // artifacts. iOS UI runs on devices and Apple-Silicon simulators (CI).
    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
            export(projects.shared)
        }
    }

    androidLibrary {
        namespace = "com.ostomate.app.compose"
        androidResources {
            enable = true
        }
        withHostTestBuilder {
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.zxing.core)
        }
        commonMain.dependencies {
            api(projects.shared)

            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)

            implementation(libs.navigation.compose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.compose.material.icons.core)

            implementation(libs.kotlinx.datetime)

            implementation(libs.koin.core)
            implementation(libs.koin.compose.viewmodel)

            implementation(libs.qrose)
        }
        // ViewModel tests (2.5.3): UiState transitions on JVM host + iOS sim, with fakes
        // at the DAO/platform-interface boundary so the real repositories are exercised.
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}

// Stamps the exact commit into the About screen so a device screenshot identifies the
// build — versionName is static and "on main" is not "on the phone" (CLAUDE.md,
// post-mortem 2026-07-12). providers.exec is configuration-cache safe.
val gitSha: Provider<String> =
    providers
        .exec { commandLine("git", "rev-parse", "--short", "HEAD") }
        .standardOutput.asText
        .map { it.trim() }

val gitDirty: Provider<String> =
    providers
        .exec { commandLine("git", "status", "--porcelain", "--untracked-files=no") }
        .standardOutput.asText
        .map { if (it.isBlank()) "" else "-dirty" }

val generateBuildInfo by tasks.registering {
    val stamp = gitSha.zip(gitDirty) { sha, dirty -> sha + dirty }
    val outDir = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    inputs.property("stamp", stamp)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("com/ostomate/app/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package com.ostomate.app
            |
            |/** Generated by :composeApp:generateBuildInfo — do not edit. */
            |object BuildInfo {
            |    /** Short git SHA this build was produced from; "-dirty" if the tree had uncommitted changes. */
            |    const val GIT_SHA: String = "${stamp.get()}"
            |}
            """.trimMargin() + "\n",
        )
    }
}

kotlin.sourceSets.commonMain {
    kotlin.srcDir(generateBuildInfo)
}

// Coverage (2.5.3, 08-test-strategy §5): ViewModel + UiState classes only — composables
// and generated Compose code would distort the signal and are exercised by E2E instead.
jacoco {
    toolVersion = libs.versions.jacoco.get()
}

val coverageClasses =
    layout.buildDirectory.dir("classes/kotlin/android/main").map { dir ->
        fileTree(dir) {
            include("com/ostomate/app/ui/**/*ViewModel*", "com/ostomate/app/ui/**/*UiState*")
        }
    }

val jacocoHostTestReport by tasks.registering(JacocoReport::class) {
    group = "verification"
    description = "Coverage report for the JVM host test run (ViewModel + UiState scope)."
    dependsOn("testAndroidHostTest")
    executionData(layout.buildDirectory.file("jacoco/testAndroidHostTest.exec"))
    classDirectories.setFrom(coverageClasses)
    sourceDirectories.setFrom(files("src/commonMain/kotlin"))
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

val jacocoCoverageVerification by tasks.registering(JacocoCoverageVerification::class) {
    group = "verification"
    description = "Fails if line coverage of the ViewModel + UiState scope drops below the floor."
    dependsOn("testAndroidHostTest")
    executionData(layout.buildDirectory.file("jacoco/testAndroidHostTest.exec"))
    classDirectories.setFrom(coverageClasses)
    sourceDirectories.setFrom(files("src/commonMain/kotlin"))
    violationRules {
        rule {
            limit {
                counter = "LINE"
                value = "COVEREDRATIO"
                // Floor = measured baseline, 93.3% on 2026-07-02 (2.5.3). Never lower.
                minimum = "0.93".toBigDecimal()
            }
        }
    }
}
